name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Copy .env file
        working-directory: .devcontainer
        run: cp .env.example ../.env

      - name: Start dev container and test
        uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer/devcontainer.json
          runCmd: |
            composer lint
            composer test
            npx playwright test